version: '3.7'
services:
  db:
    image: postgres:10
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_PASSWORD: 'password'
    volumes:
      - data:/var/lib/postgresql/data
  web:
    image: morphosisapps/saverserver:latest
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://postgres:password@db
  nginx:
    build:
      context: ..
      dockerfile: .docker/nginx/Dockerfile
    depends_on:
      - web
    ports:
      - 80:80
      - 443:443
    links:
      - web
volumes:
  data:
